spring.application.name=ShopEaseLanka
server.port=8080

# Database Configuration (Port 3307 local default)
spring.datasource.url=jdbc:mysql://localhost:3306/shopease_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo
spring.datasource.username=root
spring.datasource.password=Hiruni@1017
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Web & Static Resources
spring.web.resources.static-locations=classpath:/static/

# Jackson JSON formatting
spring.jackson.serialization.indent-output=true

#Allow data.sql seeding
spring.sql.init.mode=always
